- .idea/.gitignore
- .idea/Organizer.iml
- .idea/compiler.xml
- .idea/encodings.xml
- .idea/jarRepositories.xml
- .idea/misc.xml
- .idea/modules.xml
- Shahab
- sample upload
- target/classes/com/example/organizer/hello-view.fxml
Updating the config for intelliJ systems. Updated gitignore for more broad application of fxml.
> Inital Config

- src/main/java/com/example/organizer/User.java
> Created User class

- .idea/misc.xml
- README.md
- src/main/java/com/bookclub/dao/UserDAO.java
- src/main/java/com/bookclub/iao/IUserAO.java
- src/main/java/com/bookclub/mao/UserMAO.java
- src/main/java/com/bookclub/util/DatabaseManager.java
- src/main/java/module-info.java
- target/classes/com/bookclub/main.fxml
Set up templating of database content for Users.
Updated README to reflect the change in directory structure.
> Users Database templating.

- .idea/misc.xml
- src/main/java/com/bookclub/mao/UserMAO.java
- src/main/java/com/bookclub/model/User.java
- src/main/java/com/bookclub/service/LoginService.java
- src/test/UserTest.java
- Added username and password properties to User
- Added test directory
- Added User unit tests
- Amended UserMAO and LoginService classes to reflect new changes to the User constructor
> Add User properties and test directory

- src/main/java/com/bookclub/dao/BookDAO.java
- src/main/java/com/bookclub/iao/IBookAO.java
- src/main/java/com/bookclub/mao/BookMAO.java
- src/main/java/com/bookclub/model/Book.java
- src/main/java/com/bookclub/util/DatabaseManager.java
- src/test/BookTest.java
- Created Book class
- Created BookDAO class
- Created BookMAO class
- Created IBookAO interface
- Created Book unit tests
- Altered DatabaseManager (it just looked... strange?)
> Created Book class and Book DAO classes

- .idea/misc.xml
- src/main/java/com/bookclub/Main.java
- src/main/java/com/bookclub/controller/BooksController.java
- src/main/java/com/bookclub/controller/ReviewController.java
- src/main/java/com/bookclub/dao/ReviewDAO.java
- src/main/java/com/bookclub/iao/IBookAO.java
- src/main/java/com/bookclub/iao/IReviewAO.java
- src/main/java/com/bookclub/mao/BookMAO.java
- src/main/java/com/bookclub/mao/ReviewMAO.java
- src/main/java/com/bookclub/model/Book.java
- src/main/java/com/bookclub/model/Review.java
- src/main/java/com/bookclub/service/LoginService.java
- src/main/java/module-info.java
- src/main/resources/com/bookclub/books.fxml
- src/main/resources/com/bookclub/review.fxml
- src/test/ReviewTest.java
- target/classes/com/bookclub/books.fxml
- target/classes/com/bookclub/review.fxml
Created 5 star review system.
UI incomplete.
> Created 5 Star Review System

- src/main/java/com/bookclub/iao/IUserAO.java
- src/main/java/com/bookclub/mao/UserMAO.java
- src/main/java/com/bookclub/service/LoginService.java
Updated User Access Object, and patched up Login Service to behave as expected.
> UserMAO and LoginService fixed.

- src/main/java/com/bookclub/controller/AccountSettingsController.java
- src/main/java/com/bookclub/controller/HomeController.java
- src/main/java/com/bookclub/controller/LoginController.java
- src/main/java/com/bookclub/controller/NavigatorBarController.java
- src/main/java/com/bookclub/service/LoginService.java
- src/main/java/com/bookclub/util/StageFactory.java
- src/main/java/com/bookclub/util/StageView.java
- src/main/resources/com/bookclub/accountSettings.fxml
- src/main/resources/com/bookclub/books.fxml
- src/main/resources/com/bookclub/home.fxml
- target/classes/com/bookclub/accountSettings.fxml
- target/classes/com/bookclub/home.fxml
Implemented the skeleton for Account Settings 
- Implemented a big red SignOut button and its attached logic.
- Resolves #13
> Account settings UI skeleton (RELIES ON #53)

- pom.xml
- src/main/java/com/bookclub/model/Book.java
- src/main/java/com/bookclub/model/Review.java
- src/main/java/com/bookclub/model/User.java
- src/test/BookTest.java
- src/test/ReviewTest.java
- src/test/UserTest.java
Beefed up the tests, added some throws, added tests for these throws. 
Denoted edge case tests.
Fleshed documentation in our current Models.
Resolves #58 , Resolves #59 , Resolves #60
> Beefed Tests for User, Book, Book Review.

- src/main/java/com/bookclub/model/Event.java
- src/test/EventTest.java
Added unit tests for Event class
> Added unit tests for Event class

- src/main/resources/com/bookclub/navigatorBar.fxml
- target/classes/com/bookclub/navigatorBar.fxml
Swapped from full words to web emoticons representation.
> Nav Menu Imoticons

- .idea/misc.xml
- src/main/java/com/bookclub/Main.java
- src/main/java/com/bookclub/model/Event.java
- src/main/java/com/bookclub/util/DatabaseManager.java
- src/main/java/com/bookclub/util/PasswordHasher.java
- src/main/java/com/bookclub/util/StageFactory.java
Added documentation (javadoc comments)
Fixed typos
Removed unused fields
> Added documentation

- src/main/java/com/bookclub/dao/UserDAO.java
- src/main/java/com/bookclub/iao/IUserAO.java
- src/main/java/com/bookclub/mao/UserMAO.java
- src/main/java/com/bookclub/model/User.java
- src/main/java/com/bookclub/service/LoginService.java
- src/test/UserTest.java
- Added user IDs to the structure of User. 
- Implemented Tests
- Updated UserAO and inherited types to hold functionality for it. 
- Added an AUTOINCREMENT SQL type for implementation, and fed back the new value into the passed values.
> UserID implementation.

- .gitignore
Directory /.idea/ wasn't ignored properly.
> Fixed Git Ignore 2

- src/main/java/com/bookclub/controller/EventsController.java
- src/main/java/com/bookclub/controller/RSVPController.java
- src/main/java/com/bookclub/dao/RSVPDAO.java
- src/main/java/com/bookclub/iao/IRSVPAO.java
- src/main/java/com/bookclub/model/RSVP.java
- src/main/java/com/bookclub/service/EventService.java
- src/main/java/com/bookclub/service/RSVPService.java
- src/main/resources/com/bookclub/events.fxml
- src/main/resources/com/bookclub/rsvp.fxml
- target/classes/com/bookclub/events.fxml
- target/classes/com/bookclub/rsvp.fxml
Disabled event editing for users who didn't organise the event (this probably should've been the case in the first place)
Implemented Event RSVP functionality:
- Organiser of events cannot RSVP but can see users who have (will create another item to make this list show the RSVP status)
- Users who are not organisers can RSVP but will not be able to see other users RSVPs until they have submitted theirs
> Implemented Event RSVP

- src/main/java/com/bookclub/controller/BookProgressController.java
- src/main/java/com/bookclub/controller/BooksController.java
- src/main/java/com/bookclub/controller/ReviewController.java
- src/main/java/com/bookclub/dao/BookProgressDAO.java
- src/main/java/com/bookclub/iao/IBookProgressAO.java
- src/main/java/com/bookclub/model/BookProgress.java
- src/main/java/com/bookclub/service/BookProgressService.java
- src/main/java/com/bookclub/service/BookService.java
- src/main/resources/com/bookclub/bookProgress.fxml
- src/main/resources/com/bookclub/review.fxml
- target/classes/com/bookclub/bookProgress.fxml
- target/classes/com/bookclub/review.fxml
Added BookService (just stores the selected book for now, will add more stuff later to further refactor BookController)
Implemented reading progress tracking (currently available through the review page (sue me), its final home is still TBD)
- Users press Start to add their progress (page number)
- Users can update their page number and view other users' progress for that book (list is sorted by lowest page number)
- Users press Finish to remove their progress (UI will only show the Start button like the first image)
The logic for this will most likely change once books have a total pages field
> Implemented reading progress tracking

- src/main/java/com/bookclub/controller/AccountSettingsController.java
- src/main/java/com/bookclub/controller/RegisterController.java
- src/main/java/com/bookclub/dao/UserDAO.java
- src/main/java/com/bookclub/model/User.java
- src/main/java/com/bookclub/service/LoginService.java
- src/main/resources/com/bookclub/accountSettings.fxml
- src/main/resources/com/bookclub/register.fxml
- src/test/java/com/example/LoginServiceTests.java
- src/test/java/com/example/UserTest.java
- target/classes/com/bookclub/accountSettings.fxml
- target/classes/com/bookclub/bookProgress.fxml
- **Added name and email fields to the User class**
- **Justification**: Allows for more comprehensive user profiles and improved user identification.
- **Updated addUser and updateUser methods to include name and email**
- **Justification**: Ensures persistence of new user data fields in the database.
- **Modified register method to accept name and email parameters.**
- **Added updateUser method to handle user information updates.**
- **Justification**: Provides service-level support for new user data fields.
- **Added input fields for name and email in the registration form.**
- **Modified RegisterController to handle new fields.**
- **Justification**: Allows users to provide name and email during account creation.
- **Added fields for viewing and editing name and email.**
- **Created …
> ProfileUpdates

- src/main/java/com/bookclub/controller/RSVPController.java
- src/main/java/com/bookclub/mao/RSVPMAO.java
- src/main/java/com/bookclub/service/RSVPService.java
- src/test/java/com/example/RSVPServiceTest.java
Added RSVPMAO
Minor refactoring in RSVPService to help with testing
Added unit tests for RSVPService
> Added RSVPService tests

- src/test/java/com/example/RSVPServiceTest.java
- target/classes/com/bookclub/register.fxml
Our amazing pipeline didn't show an error at the time of merging RSVPService tests so new PR just for the fix (yay)
> Fixed tests

- src/main/java/com/bookclub/controller/ChatController.java
- src/main/java/com/bookclub/model/ChatDisplay.java
- src/main/java/com/bookclub/service/ChatService.java
- Implemented new Chat Display model
- Added a chatService manager
- Seperated data access from ChatController
- Service now creates messageDisplay content to pass over (technically ChatController doesnt need to know about chat messages, OOO is weird)
- Changed display to show the username if sent from a user that isn't the signed in user
- Fixed up some spacing stuff to accomodate
- Removed TODOs.
> ChatUI Improvements 1

- src/main/java/com/bookclub/controller/BooksController.java
- src/main/java/com/bookclub/controller/ReviewController.java
- src/main/java/com/bookclub/dao/ReviewDAO.java
- src/main/java/com/bookclub/iao/IReviewAO.java
- src/main/java/com/bookclub/mao/ReviewMAO.java
- src/main/java/com/bookclub/service/BookService.java
- src/main/resources/com/bookclub/books.fxml
In `BookService`, I added methods to calculate the average rating and retrieve the number of ratings for a book.
In `BooksController`, I updated the `updateBooks` method to display the average rating and number of ratings for each book using the new methods in `BookService`.
I had some fun while writing this code, so I fucked around in the `BookService` class—deny it if you don't see my logic:
- I implemented the Bill Pugh Singleton pattern, as it ensures thread safety and lazy initialization without requiring synchronization blocks. 
- I implemented caching for book reviews by using a simple in-memory cache with `ConcurrentHashMap` to store and retrieve review data for books. so this should minimize repeated database access for frequently accessed books.
> Implemented a 5-star average review system.

- .idea/misc.xml
- .idea/vcs.xml
- pom.xml
- src/main/java/com/bookclub/controller/BookProgressController.java
- src/main/java/com/bookclub/controller/BooksController.java
- src/main/java/com/bookclub/mao/BookProgressMAO.java
- src/main/java/com/bookclub/model/Book.java
- src/main/java/com/bookclub/service/BookProgressService.java
- src/test/java/com/example/BookProgressServiceTest.java
- src/test/java/com/example/BookTest.java
- src/test/java/com/example/ReviewTest.java
- target/classes/com/bookclub/books.fxml
Added BookProgressMAO and refactored BookProgressService to make it more testable
Amended some BookProgressService methods because they were shit
Reverted changes to misc.xml and vcs.xml from #103 (imo we should just keep the JDK/SDK the same, it's been working for us so far)
Made some temporary fixes to Book (the implementation of the genre field is probably a bit undercooked, was breaking some stuff - a new task should be made to address it)
Added BookProgress unit tests
> Added BookProgress tests

- src/main/java/com/bookclub/Main.java
- src/main/java/com/bookclub/controller/BooksController.java
- src/main/java/com/bookclub/controller/EventsController.java
- src/main/java/com/bookclub/controller/HomeController.java
- src/main/java/com/bookclub/controller/LoginController.java
- src/main/java/com/bookclub/controller/NavigatorBarController.java
- src/main/java/com/bookclub/controller/RSVPController.java
- src/main/java/com/bookclub/controller/RegisterController.java
- src/main/java/com/bookclub/controller/ReviewController.java
- src/main/java/com/bookclub/dao/EventDAO.java
- src/main/java/com/bookclub/dao/RSVPDAO.java
- src/main/java/com/bookclub/dao/ReviewDAO.java
- src/main/java/com/bookclub/iao/IBookAO.java
- src/main/java/com/bookclub/iao/IBookProgressAO.java
- src/main/java/com/bookclub/iao/IChatAO.java
- src/main/java/com/bookclub/iao/IEventAO.java
- src/main/java/com/bookclub/iao/IRSVPAO.java
- src/main/java/com/bookclub/iao/IReviewAO.java
- src/main/java/com/bookclub/iao/IUserAO.java
- src/main/java/com/bookclub/mao/RSVPMAO.java
- src/main/java/com/bookclub/mao/ReviewMAO.java
- src/main/java/com/bookclub/model/RSVP.java
- src/main/java/com/bookclub/service/RSVPService.java
- src/main/java/com/bookclub/util/PasswordHasher.java
- src/main/java/com/bookclub/util/StageFactory.java
- src/main/java/com/bookclub/util/StageView.java
Documentation added or improved for misc files that are missing some and giving javadoc a hard time.
> Documentation Improvements

- src/test/java/com/example/model/BookTest.java
- src/test/java/com/example/model/ChatMessageTest.java
- src/test/java/com/example/model/EventTest.java
- src/test/java/com/example/model/ReviewTest.java
- src/test/java/com/example/model/UserTest.java
- src/test/java/com/example/service/BookProgressServiceTest.java
- src/test/java/com/example/service/LoginServiceTests.java
- src/test/java/com/example/service/RSVPServiceTest.java
Breaking up the directory handling for the tests so they're easier to recognise where the Tests are handled, also allowing us to handle batches (it's not super useful to run all of the Models when we're interested in Services, etc.)
> Breaking up content for tests to directories.

- src/main/java/com/bookclub/model/BookProgress.java
- src/main/java/com/bookclub/model/RSVP.java
- src/test/java/com/example/model/BookProgressTest.java
- src/test/java/com/example/model/RSVPTest.java
Remainder of the tests we were missing for the current models.
> Model Tests

- src/test/java/com/example/util/PasswordHasherTest.java
Should have unit tests for a password hasher. Could do with more tests.
> PasswordHasher Tests

- src/main/java/com/bookclub/mao/RSVPMAO.java
- src/main/java/com/bookclub/mao/ReviewMAO.java
- src/main/java/com/bookclub/mao/UserMAO.java
- src/main/java/com/bookclub/model/Review.java
- src/test/java/com/example/mao/RSVPMAOTest.java
- src/test/java/com/example/mao/ReviewMAOTest.java
- src/test/java/com/example/mao/UserMAOTest.java
The last of the MAO tests for now until functional improvements.
> More MAO Test

- src/main/java/com/bookclub/dao/EventDAO.java
Apparently the build script didn't catch the merge error.
> Fixed Master

- src/main/java/com/bookclub/controller/ReviewController.java
- src/main/java/com/bookclub/dao/ReviewDAO.java
- src/main/java/com/bookclub/mao/ReviewMAO.java
- src/main/java/com/bookclub/model/Review.java
- src/main/resources/com/bookclub/review.fxml
- src/test/java/com/example/mao/ReviewMAOTest.java
- src/test/java/com/example/model/ReviewTest.java
Added field for Users to write in debt Review (Topic an Description of review) as well as rating. users can either write reviews and rate the books or just rate the books without needing to write a review. The screen shot shows list of 4 registered users adding reviews and rating books/ only rating books with no reviews and update comments by resubmitting an edited or new comment. The the fields for the review topic and description had been added
to the bookclub.db database under reviews. (This is the fixed version)
> Book Review/Rating implementation and fixes
